language: objective-c
osx_image: xcode8
env:
    global:
    - PROJECT=Framezilla.xcodeproj
    - IOS_FRAMEWORK_SCHEME="Framezilla iOS"
    - IOS_SDK=iphonesimulator10.0
    matrix:
    - DESTINATION="OS=10.0,name=iPhone 7 Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"

script:
    - set -o pipefail
    - xcodebuild -project "$PROJECT" -scheme "$IOS_FRAMEWORK_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" build test | xcpretty -c --test --color
